version: '3'

services:
  moodle:
    image: moodlehq/moodle-php-apache:4.0
    ports:
      - 80:80
    volumes:
      - moodledata:/var/moodledata
      - ./moodle:/var/www/html
    environment:
      - MOODLE_DB_TYPE=mysqli
      - MOODLE_DB_HOST=database
      - MOODLE_DB_NAME=moodle
      - MOODLE_DB_USER=moodle
      - MOODLE_DB_PASSWORD=your_password
      - MOODLE_DB_PREFIX=mdl_
    depends_on:
      - database
    networks:
      - moodle_net

  database:
    image: mysql:5.7
    environment:
      - MYSQL_DATABASE=moodle
      - MYSQL_USER=moodle
      - MYSQL_PASSWORD=your_password
      - MYSQL_ROOT_PASSWORD=your_root_password
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - moodle_net

networks:
  moodle_net:

volumes:
  moodledata:
  dbdata:
