version: '3'

services:
  moodle:
    image: moodlehq/moodle-php-apache:4.0
    ports:
      - 80:80
    volumes:
      - moodledata:/var/moodledata
      - ./moodle:/var/www/html
    depends_on:
      - database
    networks:
      - moodle_net

  database:
    image: mysql:5.7
    environment:
      - MYSQL_DATABASE=moodle
      - MYSQL_USER=moodle
      - MYSQL_PASSWORD=User4moodle
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - moodle_net

networks:
  moodle_net:

volumes:
  moodledata:
  dbdata:
