version: '3.9'

services:
  mariadb:
    image: "mariadb"
    networks:
      - moodle
    environment:
      - MARIADB_DATABASE=moodle
      - MARIADB_USER=moodleadmin
      - MARIADB_PASSWORD=Riethuesli>12345
      - MARIADB_RANDOM_ROOT_PASSWORD=true
    volumes:
      - mariadb_data:/var/lib/mysql
  

  moodle:
    image: bitnami/moodle:4.1
    ports:
      - '80:8080'
      - '8443:8443'
    environment:
      - MOODLE_DATABASE_HOST=mariadb
      - MOODLE_DATABASE_NAME=moodle
      - MOODLE_DATABASE_USER=moodleadmin
      - MOODLE_DATABASE_PASSWORD=Riethuesli>12345
    volumes:
      - moodle_data:/bitnami/moodle
      - moodledata_data:/bitnami/moodledata
    networks:
      - moodle

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8888:80
    environment:
      - PMA_HOST=mariadb
    networks:
      - moodle

networks:
  moodle-net:
    driver: bridge

volumes:
  mariadb_data:
  moodle_data:
  moodledata_data:
